[id]
name = spl_scratchbook
version = 1.0.2

[install]
is_configured = 0
state = enabled

[package]
id = spl_scratchbook
check_for_updates = false

[ui]
is_visible = 1
label = SPL Scratchbook

[launcher]
author = G0TH3R
description = A notebook-style workspace for formatting and running stacked SPL searches.
version = 1.0.2

[triggers]
reload.nav = simple
reload.ui = simple
reload.metadata = simple
